from .auteur import AuteurViewSet
from .livre import LivreViewSet
from .categorie import CategorieViewSet
from .commentaire import CommentaireViewSet
from .editeur import EditeurViewSet
from .emprunt import EmpruntViewSet
from .evaluation import EvaluationViewSet
from .exemplaire import ExemplaireViewSet
from .auth import AuteurViewSet
from .security import MySecureView
